<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-06-20 22:57
=======
# Generated by Django 5.0.3 on 2024-06-20 22:49
>>>>>>> 0efb905850fe4faf00212ad8affa63a1aa3715b2

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("writer", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=30)),
                ("body", models.TextField()),
                ("pub_date", models.DateTimeField()),
=======

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField()),
>>>>>>> 0efb905850fe4faf00212ad8affa63a1aa3715b2
            ],
        ),
    ]
