# Generated by Django 4.2.13 on 2024-06-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careers", "0002_careerinfo_delete_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerinfo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="careerinfo/"),
        ),
    ]
