# Generated by Django 4.2.13 on 2024-06-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careers", "0004_careerinfo_writer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Careerinfotag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name="careerinfo",
            old_name="place",
            new_name="field",
        ),
        migrations.AddField(
            model_name="careerinfo",
            name="startline",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="careerinfo",
            name="careerinfotags",
            field=models.ManyToManyField(
                blank=True, related_name="careerinfos", to="careers.careerinfotag"
            ),
        ),
    ]
