# Generated by Django 4.2.13 on 2024-06-22 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("careers", "0006_careerinfo_ci_bm_careerinfo_cibm_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Careerprogramtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Careerprogram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("startline", models.CharField(default="", max_length=20)),
                ("deadline", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=30)),
                ("field", models.CharField(max_length=10)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="careerprogram/"
                    ),
                ),
                ("pub_date", models.DateTimeField()),
                ("cpbm_count", models.PositiveIntegerField(default=0)),
                (
                    "careerprogramtags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="careerprograms",
                        to="careers.careerprogramtag",
                    ),
                ),
                (
                    "cp_bm",
                    models.ManyToManyField(
                        blank=True, related_name="cp_bms", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
