# Generated by Django 5.0.4 on 2024-06-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board_sort",
                    models.CharField(
                        choices=[("이직", "이직"), ("자유", "자유")], max_length=10
                    ),
                ),
                ("board_title", models.CharField(max_length=255)),
                ("board_content", models.TextField()),
                ("board_image", models.ImageField(upload_to="images/")),
                ("board_tag", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Community",
        ),
    ]
