# Generated by Django 5.0.4 on 2024-06-21 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_board_delete_community"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="board_sort",
        ),
    ]
