# Generated by Django 5.0.4 on 2024-06-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_remove_board_board_sort"),
    ]

    operations = [
        migrations.CreateModel(
            name="Free",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("image", models.ImageField(upload_to="images/")),
                ("tag", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("pub_date", models.DateTimeField()),
                ("image", models.ImageField(upload_to="images/")),
                ("tag", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Board",
        ),
    ]
