# Generated by Django 5.0.4 on 2024-06-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_free_move_delete_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="free",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="free/"),
        ),
        migrations.AlterField(
            model_name="move",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="move/"),
        ),
    ]
