# Generated by Django 5.0.4 on 2024-06-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0007_freecomment_movecomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Freetag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("freename", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Movetag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movename", models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name="free",
            name="tag",
        ),
        migrations.RemoveField(
            model_name="move",
            name="tag",
        ),
        migrations.AddField(
            model_name="free",
            name="freetag",
            field=models.ManyToManyField(
                blank=True, related_name="frees", to="community.freetag"
            ),
        ),
        migrations.AddField(
            model_name="move",
            name="movetag",
            field=models.ManyToManyField(
                blank=True, related_name="moves", to="community.movetag"
            ),
        ),
    ]
