# Generated by Django 5.0.4 on 2024-06-21 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0008_freetag_movetag_remove_free_tag_remove_move_tag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="free",
            old_name="freetag",
            new_name="freetags",
        ),
        migrations.RenameField(
            model_name="move",
            old_name="movetag",
            new_name="movetags",
        ),
    ]
