# Generated by Django 4.2.13 on 2024-06-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0011_free_ftcontent_alter_free_emoji"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="mtcontent",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
