# Generated by Django 5.0.6 on 2024-06-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_move_mtcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='emoji',
            field=models.TextField(),
        ),
    ]
