# Generated by Django 5.0.6 on 2024-06-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0012_move_mtcontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="move",
            name="emoji",
            field=models.TextField(),
        ),
    ]
