# Generated by Django 4.2.13 on 2024-06-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0012_move_mtcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="field",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="move",
            name="emoji",
            field=models.TextField(),
        ),
    ]
