# Generated by Django 5.0.4 on 2024-06-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_enroll",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_major",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
