# Generated by Django 5.0.6 on 2024-06-20 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50)),
                ('user_phone', models.CharField(default='', max_length=50)),
                ('user_birth', models.DateField(default='2000-01-01')),
                ('user_major', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user_profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user_enroll', models.CharField(blank=True, choices=[('재학', '재학'), ('휴학', '휴학'), ('졸업', '졸업'), ('교직원', '교직원')], default='', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Community',
        ),
    ]
