# Generated by Django 5.0.4 on 2024-06-18 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_profile_user_enroll_alter_profile_user_major"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="updated_at",
        ),
    ]
