# Generated by Django 5.0.4 on 2024-06-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_birth",
            field=models.IntegerField(),
        ),
    ]
