# Generated by Django 5.0.4 on 2024-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_profile_user_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_birth",
            field=models.DateField(),
        ),
    ]
