# Generated by Django 5.0.3 on 2024-06-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_menti_ship_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='menti_ship',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_ship', to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
