# Generated by Django 5.0.3 on 2024-06-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_menti_ship_delete_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='menti_ship',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_ship', to='accounts.profile'),
        ),
    ]
