# Generated by Django 5.0.4 on 2024-06-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_profile_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_birth",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_enroll",
            field=models.CharField(
                blank=True,
                choices=[("재학", "재학"), ("휴학", "휴학"), ("졸업", "졸업"), ("교직원", "교직원")],
                default="",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_major",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_phone",
            field=models.CharField(default="", max_length=50),
        ),
    ]
