# Generated by Django 4.2.13 on 2024-06-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_remove_profile_menti_ship_profile_menti_ship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_profile",
            field=models.ImageField(
                blank=True,
                default="default_profile.png",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
