# Generated by Django 5.0.3 on 2024-06-20 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_company', models.CharField(max_length=50)),
                ('mentor_dept', models.CharField(max_length=50)),
                ('mentor_work', models.CharField(max_length=50)),
                ('mentor_summary', models.CharField(max_length=50)),
                ('mentor_info', models.TextField(max_length=300)),
                ('mentor_career', models.CharField(max_length=50)),
                ('mentor_certificate', models.CharField(blank=True, max_length=100, null=True)),
                ('mentor_id_card', models.ImageField(upload_to='mentor_1/')),
                ('mentor_name_card', models.ImageField(upload_to='mentor_2/')),
                ('follow_count', models.PositiveIntegerField(default=0)),
                ('mentor_at', models.DateTimeField()),
                ('follow', models.ManyToManyField(blank=True, related_name='follow', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
