# Generated by Django 5.0.4 on 2024-06-20 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mentor_company", models.CharField(default="", max_length=50)),
                ("mentor_dept", models.CharField(default="", max_length=50)),
                ("mentor_work", models.CharField(default="", max_length=50)),
                ("mentor_summary", models.CharField(default="", max_length=50)),
                ("mentor_info", models.TextField(default="", max_length=300)),
                ("mentor_career", models.CharField(default="", max_length=50)),
                (
                    "mentor_certificate",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "mentor_id_card",
                    models.ImageField(default="", upload_to="mentor_1/"),
                ),
                (
                    "mentor_name_card",
                    models.ImageField(default="", upload_to="mentor_2/"),
                ),
                ("mentor_at", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
