# Generated by Django 5.0.3 on 2024-06-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mento',
            new_name='Mentor',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mento_at',
            new_name='mentor_at',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mento_company',
            new_name='mentor_company',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mento_dept',
            new_name='mentor_dept',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mento_intro',
            new_name='mentor_intro',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mento_work',
            new_name='mentor_work',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='mento_year',
            new_name='mentor_year',
        ),
    ]
