# Generated by Django 5.0.3 on 2024-06-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_user_birth_alter_profile_user_enroll_and_more'),
        ('main', '0003_remove_mentor_mentor_name_mentor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
