# Generated by Django 5.0.3 on 2024-06-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mentor_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='profile',
        ),
    ]
