# Generated by Django 5.0.3 on 2024-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_mentor_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='mentor_intro',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='mentor_year',
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_career',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_certificate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_id_card',
            field=models.ImageField(default='', upload_to='mentor_1/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_info',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_name_card',
            field=models.ImageField(default='', upload_to='mentor_2/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='mentor_summary',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
