# Generated by Django 5.0.3 on 2024-06-21 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_mentor_follow_remove_mentor_follow_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='mentor_followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
