# Generated by Django 5.0.3 on 2024-06-22 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_mentor_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentor_ship',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='menti_ship', to='main.mentor'),
            preserve_default=False,
        ),
    ]
