# Generated by Django 5.0.3 on 2024-06-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mentor_mentor_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentor_ship',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='menti_ship', to='main.mentor'),
        ),
    ]
