# Generated by Django 5.0.3 on 2024-06-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_mentor_mentor_ship_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='mentor_ship',
            field=models.ForeignKey(blank=True, default='0', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menti_ship', to='main.mentor'),
        ),
        migrations.DeleteModel(
            name='Accept',
        ),
    ]
