# Generated by Django 5.0.3 on 2024-06-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_mentor_mentor_ship_delete_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentor_ship',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menti_ship', to='main.mentor'),
        ),
    ]
