# Generated by Django 5.0.3 on 2024-06-23 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_menti_ship_profile_menti_ship'),
        ('main', '0013_remove_mentor_mentor_ship_mentor_mentor_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
