# Generated by Django 5.0.3 on 2024-06-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_menti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mentor_ship',
            field=models.ManyToManyField(blank=True, related_name='menti_ship', to='main.mentor'),
        ),
        migrations.DeleteModel(
            name='Menti',
        ),
    ]
