# Generated by Django 5.0.3 on 2024-06-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_relation_mentor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation_mentor',
            old_name='menti_id',
            new_name='menti',
        ),
        migrations.RenameField(
            model_name='relation_mentor',
            old_name='mentor_id',
            new_name='mentor',
        ),
    ]
