# Generated by Django 5.0.3 on 2024-06-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_menti'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation_mentor',
            name='mentoring_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
